# Regresión lineal en Python

## El paquete scikit-learn para regresión lineal y selección de rasgos

In [3]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [4]:
urldata = "https://raw.githubusercontent.com/joanby/python-ml-course/master/datasets/ads/Advertising.csv"

In [5]:
data = pd.read_csv(urldata)

In [6]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [7]:
X = data[feature_cols]
Y = data["Sales"]

In [9]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step=1)
selector = selector.fit(X,Y)

C:\Users\LGARAVITO2\anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [10]:
selector.support_

array([ True,  True, False])

In [11]:
selector.ranking_

array([1, 1, 2])

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
X_pred = X[["TV", "Radio"]]

In [14]:
lm = LinearRegression()
lm.fit(X_pred, Y) 

LinearRegression()

In [16]:
lm.intercept_

2.9210999124051344

In [17]:
lm.coef_

array([0.04575482, 0.18799423])

In [18]:
lm.score(X_pred, Y)

0.8971942610828956