# El método de k-means

In [1]:
import numpy as np

In [3]:
data = np.random.random(90).reshape(30,3)
data

array([[0.23897197, 0.60070211, 0.02129658],
       [0.31560278, 0.86251683, 0.06250271],
       [0.88905385, 0.19679317, 0.07646475],
       [0.68917687, 0.05538426, 0.58975286],
       [0.16523751, 0.11827145, 0.10331374],
       [0.05636819, 0.59668709, 0.5970692 ],
       [0.22561446, 0.29607415, 0.62657422],
       [0.58894317, 0.68026801, 0.66010201],
       [0.1991904 , 0.39383328, 0.82270975],
       [0.40146784, 0.15588877, 0.53878538],
       [0.76804519, 0.67223593, 0.44045764],
       [0.65463658, 0.01294749, 0.11337366],
       [0.53114379, 0.83142702, 0.74712212],
       [0.80432378, 0.95560837, 0.79841866],
       [0.46924298, 0.69982939, 0.33320827],
       [0.83848138, 0.69529071, 0.01424135],
       [0.44732687, 0.25855807, 0.17496231],
       [0.54072181, 0.33486994, 0.37942646],
       [0.74509257, 0.84622217, 0.09287931],
       [0.27508253, 0.06280794, 0.48678257],
       [0.79224458, 0.64154257, 0.47964001],
       [0.50772175, 0.20403104, 0.86630564],
       [0.

In [5]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.22561446, 0.29607415, 0.62657422],
       [0.03785693, 0.44197973, 0.66733306]])

In [6]:
from scipy.cluster.vq import vq

In [7]:
vq(data, clust_centers)

(array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 0]),
 array([0.67774452, 0.78728264, 0.86754191, 0.52361965, 0.55593228,
        0.17092116, 0.        , 0.52984601, 0.22073565, 0.2414192 ,
        0.68583392, 0.7263577 , 0.62807855, 0.89410312, 0.5553708 ,
        0.95390318, 0.50449695, 0.40234285, 0.92593229, 0.27640897,
        0.67971155, 0.38148081, 0.7737647 , 0.49690465, 0.74050181,
        0.49682447, 0.        , 0.37633787, 0.41445465, 0.529472  ]))

In [8]:
from scipy.cluster.vq import kmeans

In [9]:
kmeans(data, clust_centers)

(array([[0.60755237, 0.34815522, 0.36870307],
        [0.34452106, 0.65130526, 0.52306135]]),
 0.3841335082628313)

In [10]:
kmeans(data, 2)

(array([[0.53873208, 0.71362662, 0.42896878],
        [0.44196077, 0.21197008, 0.44316065]]),
 0.3591014766919454)